<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>tas</string>
		<string>tass</string>
		<string>tass64</string>
	</array>
	<key>name</key>
	<string>6502 Assembly (Tass)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#asm_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#asm_controls</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#xy_registers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tass_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#labels</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#local_labels</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hex_numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#decimal_numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#binary_numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#memory_pointer</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>asm_controls</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(bcc|bcs|beq|bmi|bne|bpl|brk|bvc|bvs|jmp|jsr|rti|rts)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<key>asm_keywords</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(adc|and|asl|bit|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|sbc|sec|sed|sei|sta|stx|sty|tax|txa|tay|tya|tsx|txs)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<key>binary_numbers</key>
		<dict>
			<key>match</key>
			<string>#?%[0-1]+</string>
			<key>name</key>
			<string>constant.numeric.64tass.binary</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.64tass</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.64tass</string>
		</dict>
		<key>decimal_numbers</key>
		<dict>
			<key>match</key>
			<string>#?[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.64tass.decimal</string>
		</dict>
		<key>hex_numbers</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.64tass.dollar.sign</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#?(\$)[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.64tass.hexadecimal</string>
		</dict>
		<key>labels</key>
		<dict>
			<key>match</key>
			<string>^\w*</string>
			<key>name</key>
			<string>entity.name.64tass.label</string>
		</dict>
		<key>local_labels</key>
		<dict>
			<key>match</key>
			<string>^\.\w*</string>
			<key>name</key>
			<string>entity.name.64tass.label.local</string>
		</dict>
		<key>memory_pointer</key>
		<dict>
			<key>match</key>
			<string>\B\* *?\=\B</string>
			<key>name</key>
			<string>punctuation.definition.64tass.star.equals</string>
		</dict>
		<key>tass_types</key>
		<dict>
			<key>match</key>
			<string>(?i)\.\b(byte|hex|set|word|null|text)\b</string>
			<key>name</key>
			<string>storage.type.64tass</string>
		</dict>
		<key>xy_registers</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(x|y)\b</string>
			<key>name</key>
			<string>storage.register.64tass</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.assembly.64tass</string>
	<key>uuid</key>
	<string>471A8674-8179-4C84-AAC4-4DF02E4558CA</string>
</dict>
</plist>
